# -*- coding: utf-8 -*-
"""Sprint3_Streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Oo6YnKpOZmJUbzA9kBMvG-KuQpHA8zhm
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import pickle
# import streamlit as st
# import pandas as pd
# 
# @st.cache()
# # defining the function which will make the prediction using the data which the user inputs 
# def prediction(store,data):
#     df = data[data['store_id']==store]
#     X_train = df[(df['d']>=1914) & (df['d']<1942)].drop('sold',axis=1)
#     
#     filename ='model'+store+'.pkl'
#     pickle_in = open(filename, 'rb') 
#     classifier = pickle.load(pickle_in)
#  
#     # Making predictions 
#     prediction = classifier.predict([X_train])
#      
#     return classifier
#       
#   
# # this is the main function in which we define our webpage  
# def main():  
#     data = pd.read_pickle('/content/drive/MyDrive/data.pkl')     
#     html_temp = """ 
#     <div style ="background-color:yellow;padding:13px"> 
#     <h1 style ="color:black;text-align:center;">Streamlit Sales Prediction ML App</h1> 
#     </div> 
#     """
#       
#     st.markdown(html_temp, unsafe_allow_html = True) 
#       
#     # following lines create boxes in which user can enter data required to make prediction 
#     Store = st.selectbox('Store',("CA_1","CA_2","CA_3","CA_4","TX_1","TX_2","TX_3","WI_1","WI_2","WI_3"))
#     result =""
#       
#     # when 'Predict' is clicked, make the prediction and store it 
#     if st.button("Predict"): 
#         result = prediction(Store,data) 
#         st.success(result)
#     
#      
# if __name__=='__main__': 
#     main()

!pip install pyngrok

!pip install streamlit

from pyngrok import ngrok
 
public_url = ngrok.connect('8501')
public_url

!streamlit run /content/app.py & npx localtunnel --port 8501

